server:
  port: 9095
spring:
  application:
      name: kafka-app
  kafka:
    properties:
       security:
          protocol: SSL
    ssl:
         truststore-location: file:/C:/security/truststore.jks
         truststore-password: fastdata
         keystore-location: file:/C:/security/client.jks
         keystore-password: fastdata
         key-password: fastdata	
    topic: test.topic2
    bootstrap-servers: localhost:9093  
    producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.apache.kafka.common.serialization.StringSerializer
     
     
     
       
